#!/bin/sh

dialog_get_width() {
	s="`dialog --stdout --print-maxsize`"
	w=`echo "$s" | cut -d" " -f3`
	echo $w
}

dialog_get_height() {
	s="`dialog --stdout --print-maxsize`"
	h=`echo "$s" | cut -d" " -f2`
	echo ${h%,}
}


main_dialog() {
	max_width=`dialog_get_width`
	max_height=`dialog_get_height`

	height=$(( $max_height - 6 ))
	width=$(( $max_width - 6 ))
	height=17
	width=38
	menu_height=10

	x=0
	while [ -n "$x" -a "$x" != "X" ]; do
		x=$(dialog --stdout --title "SaveGame Options" \
			--backtitle "SaveGame Backup" \
			--menu "Choose an action" \
			$height $width $menu_height \
			"X" "Exit" \
			"1" "Backup all savegames" \
			"2" "Backup savegames" \
			"3" "Final backup savegames" \
			"4" "Restore all savegames" \
			"5" "Restore savegames" \
			"6" "Delete savegames"	\
			"7" "Delete savegame-backups"\
			"8" "Edit game.conf" \
			"9" "Add a Game")
		echo "x: $x"
		case $x in
			1)
				#backup_all
				;;
			2)
				#select_backup
				;;
			3)
				#select_final_backup
				;;
			4)
				#restore_all_savegames
				;;
			5)
				#select_restore_savegame
				;;
			7)
				#delete_savegame_backups
				;;
			8)
				#edit_game_conf
				;;
			9)
				#add_game
				;;

			"")
				;&
			X)
				;&
			*)
				break;
				;;
		esac
	done
}


main_dialog
